services:
    db:
        container_name: swim-db
        image: mysql
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    app:
        container_name: app
        links:
            - "db"
        build: ./bot
        ports:
            - "5001:5000"